// Auto-generated Bridge Client
// Do not edit this file manually

import type { ObjectContext } from '@restatedev/restate-sdk';

export interface BridgeConfig {
  SOMA_BASE_URL?: string;
}

interface InvokeResult<T> {
  type: 'success' | 'error';
  data?: T;
  error?: { message: string };
}

/**
 * Internal helper to invoke a bridge function
 */
async function invokeBridgeFunction<TParams, TResult>(
  ctx: ObjectContext,
  providerName: string,
  accountName: string,
  functionName: string,
  providerInstanceId: string,
  functionControllerTypeId: string,
  params: TParams,
  baseUrl: string
): Promise<TResult> {
  ctx.console.log(`Invoking ${providerName}.${accountName}.${functionName}`);

  const result = await ctx.run(`fetch-${providerName}-${functionName}`, async () => {
    const response = await fetch(
      `${baseUrl}/api/bridge/v1/provider/${providerInstanceId}/function/${functionControllerTypeId}/invoke`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ params }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`HTTP ${response.status}: ${errorText}`);
    }

    const result: InvokeResult<TResult> = await response.json();

    if (result.type === 'error') {
      throw new Error(result.error?.message || 'Unknown error');
    }

    return result.data as TResult;
  });

  ctx.console.log(`Completed ${providerName}.${accountName}.${functionName}`);
  return result;
}

// Type definitions for all functions




export interface Bridge {
  
}

export type BridgeDefinition = Bridge;

export function getBridge(ctx: ObjectContext, config?: BridgeConfig): Bridge {
  const baseUrl = config?.SOMA_BASE_URL || process.env.SOMA_SERVER_BASE_URL || 'http://localhost:3000';
  

  return {
    
  };
}
